server:
  port: 8080
spring:
  application:
    name: client-user
eureka:
  instance:
    instance-id: user
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:6061/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
      circuitBreaker:
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds : 2000   #时间
  threadpool:
    default:
      coreSize: 10  # 全局配置
#    getPower:
#      coreSize: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'